SET ECHO OFF
SET TERMOUT OFF
SET FEEDBACK OFF
SET PAGESIZE 0
SET LINESIZE 1000
SET TRIMSPOOL ON
COL filename new_value filename
SELECT 'U:\Data\C4_G28_'||TO_CHAR(SYSDATE,'MMDDYYYY')||'.TXT' filename FROM DUAL;
SPOOL &&filename
PROMPT APP_ID^FORM_NBR^OFFICE_LOC_CODE^OFFICE_LOC_SUB_CODE^CASE_LOC_CODE^CASE_LOC_SUB_CODE^ALIEN_NBR^LAST_NAME^FIRST_NAME^MIDDLE_NAME^DOB_DT^MR_RECV_DTIME^COB_CODE^FIRM_NAME^REP_LAST_NAME^REP_FIRST_NAME^REP_MIDDLE_NAME^BLDG_RM^STREET_NBR^STREET_NAME^CITY^STATE_CODE^ZIP_CODE^PROVINCE^POSTAL_CODE^CNTRY_CODE^UPDATED_DATETIME
SELECT
apl.APP_ID||'^'||
apl.FORM_NBR||'^'||
proc.OFFICE_LOC_CODE||'^'||
proc.OFFICE_LOC_SUB_CODE||'^'||
proc.CASE_LOC_CODE||'^'||
proc.CASE_LOC_SUB_CODE||'^'||
applic.ALIEN_NBR||'^'||
applic.LAST_NAME||'^'||
applic.FIRST_NAME||'^'||
applic.MIDDLE_NAME||'^'||
TO_CHAR(applic.DOB_DT,'MM/DD/YYYY')||'^'||
TO_CHAR(apl.MR_RECV_DTIME,'MM/DD/YYYY')||'^'||
applic.COB_CODE||'^'||
rep.FIRM_NAME||'^'||
rep.LAST_NAME||'^'||
rep.FIRST_NAME||'^'||
rep.MIDDLE_NAME||'^'||
rep.BLDG_RM||'^'||
rep.STREET_NBR||'^'||
rep.STREET_NAME||'^'||
rep.CITY||'^'||
rep.STATE_CODE||'^'||
rep.ZIP_CODE||'^'||
rep.PROVINCE||'^'||
rep.POSTAL_CODE||'^'||
rep.CNTRY_CODE||'^'||
TO_CHAR(rep.UPDATED_DATETIME,'MM/DD/YYYY')
FROM 
IBS_AP_APPLICATION apl,
IBS_AP_APPLICANT applic,
IBS_WF_PROCESS_INST proc,
IBS_AP_REPRESENTATIVE rep
WHERE 
apl.APP_ID = applic.APP_ID
AND apl.APP_ID = proc.PROCESS_INST_ID 
AND apl.REP_ID = rep.REP_ID 
-- DWP 2017/06/29 USCISC4-342: Excluding military, military spouse, and BCT cases
AND NVL(apl.MILITARY, 'N') <> 'Y'
AND NVL(apl.MILITARY_SPOUSE, 'N') <> 'Y'
AND NVL(apl.BCT_INDICATOR, 'N') <> 'Y'
AND apl.FORM_NBR in ('N336','N400','N600','N600K')
AND proc.rec_sc_loc_code ='NBC'
AND proc.PROCESS_STATE in ('Active','Suspended','Running')
AND rep.UPDATED_DATETIME > SYSDATE -30;
SPOOL OFF;
SET ECHO ON
SET TERMOUT ON
SET FEEDBACK ON
