SET ECHO OFF
SET TERMOUT OFF
SET FEEDBACK OFF
SET PAGESIZE 0
SET LINESIZE 600
SET TRIMSPOOL ON
COL filename new_value filename
SELECT 'U:\Data\C4_FBI_NAME_CHECK_'||TO_CHAR(SYSDATE,'MMDDYYYY')||'.TXT' filename FROM DUAL;
SPOOL &&filename
PROMPT APP_ID^FORM_NBR^OFFICE_LOC_CODE^OFFICE_LOC_SUB_CODE^CASE_LOC_CODE^CASE_LOC_SUB_CODE^ALIEN_NBR^LAST_NAME^FIRST_NAME^MIDDLE_NAME^DOB_DT^MR_RECV_DTIME^COB_CODE^CITIZENSHIP_CNTRY_CODE^PERMRES_DT^DISABILITY_FLAG^FORM_N648_ATTACHED_FLAG^ELIGIBILITY_CODE^CREATE_DTIME^RESPONSE_TYPE_CODE^MODIFIED_RESPONSE_CODE^MODIFIED_REASON^MODIFIED_DTIME^FBI_RESPONSE_CODE^RESPONSE_CODE^RESPONSE_DT
SELECT
apl.APP_ID||'^'||
apl.FORM_NBR||'^'||
proc.OFFICE_LOC_CODE||'^'||
proc.OFFICE_LOC_SUB_CODE||'^'||
proc.CASE_LOC_CODE||'^'||
proc.CASE_LOC_SUB_CODE||'^'||
applic.ALIEN_NBR||'^'||
applic.LAST_NAME||'^'||
applic.FIRST_NAME||'^'||
applic.MIDDLE_NAME||'^'||
TO_CHAR(applic.DOB_DT,'MM/DD/YYYY')||'^'||
TO_CHAR(apl.MR_RECV_DTIME,'MM/DD/YYYY')||'^'||
applic.COB_CODE||'^'||
applic.CITIZENSHIP_CNTRY_CODE||'^'||
TO_CHAR(applic.PERMRES_DT,'MM/DD/YYYY')||'^'||
decode(apl.DISABILITY_FLAG,'N','','Y','D') || 
   decode(apl.HEARING_IMPAIRED_FLAG,'N','','Y','H') || 
   decode(apl.WHEEL_CHAIR_FLAG,'N','','Y','W') ||
   decode(apl.VISION_IMPAIRED_FLAG,'N','','Y','V') || 
   decode(apl.OTHER_DISABILITY_FLAG, 'N','','Y','O')||'^'||
apl.FORM_N648_ATTACHED_FLAG||'^'||
apl.PART21_CODE||'^'||
TO_CHAR(fbi.CREATE_DTIME,'MM/DD/YYYY')||'^'||
fbi.RESPONSE_TYPE_CODE||'^'||
fbi.MODIFIED_RESPONSE_CODE||'^'||
fbi.MODIFIED_REASON||'^'||
TO_CHAR(fbi.MODIFIED_DTIME,'MM/DD/YYYY')||'^'||
fbi.FBI_RESPONSE_CODE||'^'||
fbi.RESPONSE_CODE||'^'||
TO_CHAR(fbi.RESPONSE_DT,'MM/DD/YYYY')
FROM 
IBS_AP_APPLICATION apl,
IBS_AP_APPLICANT applic,
IBS_WF_PROCESS_INST proc,
IBS_AP_FBI_RESPONSE fbi
WHERE 
apl.APP_ID = applic.APP_ID
AND apl.APP_ID = proc.PROCESS_INST_ID
AND apl.APP_ID = fbi.app_id-- DWP 2017/06/29 USCISC4-342: Excluding military, military spouse, and BCT cases
AND NVL(apl.MILITARY, 'N') <> 'Y'
AND NVL(apl.MILITARY_SPOUSE, 'N') <> 'Y'
AND NVL(apl.BCT_INDICATOR, 'N') <> 'Y'
AND apl.FORM_NBR = 'N400'
AND proc.rec_sc_loc_code = 'NBC'
AND proc.process_state in ('Active','Running','Suspended')
AND fbi.RESPONSE_TYPE_CODE = 'N'
AND fbi.RESPONSE_DT = (SELECT MAX(fbi1.RESPONSE_DT) 
                         FROM IBS_AP_FBI_RESPONSE fbi1
                	 WHERE fbi1.APP_ID = apl.APP_ID
                      	   AND fbi1.RESPONSE_TYPE_CODE = 'N'
			   AND fbi1.RESPONSE_DT > sysdate -30);
SPOOL OFF;
SET ECHO ON
SET TERMOUT ON
SET FEEDBACK ON

